version: '3.9'
services:
  pottery-api:
    image: emilesherrott/pottery-api-cloud:latest
    ports:
      - '80:80'
    restart: always
    depends_on:
      - pottery-db
      - pottery-python
    environment:
      PORT: 80
      PYTHON_PORT: 3000
      JAVA_PORT: 8080
      DB_USER: postgres
      DB_PORT: 5432
      DB_HOST: pottery-db
      DB_PASSWORD: "p8K#v1zQhR7@tL2"
      DB_NAME: pottery
      SECRET_TOKEN: "63eadb34645166d645f0bad4fc560bfe301ecb711fe73581299e695d275e3072"
    networks:
      - pottery-network

  java-logger:
    image: emilesherrott/java-logger-cloud:latest
    ports:
      - '8080:8080'
    restart: always
    networks:
      - pottery-network

  pottery-db:
    image: emilesherrott/pottery-db-cloud:latest
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: "p8K#v1zQhR7@tL2"
      POSTGRES_DB: "pottery"
    networks:
      - pottery-network
  
  pottery-python:
    image: emilesherrott/pottery-python-cloud:latest
    ports:
      - '3000:3000'
    restart: always
    environment:
      PORT: 3000
    networks:
      - pottery-network

networks:
  pottery-network:
